### ISSUE TITLE
Include a config file to control which test to execute

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-sandbox/artillery-service#8]
As a user, I want to be able to define which tests to be executed based on some form of a configuration file.

A first starting point could be a file somewhat similar to this:
```
---
spec_version: '0.1.0'
workloads:
  - teststrategy: performance_heavy
    script: ./performance.yaml
  - teststrategy: performance_light
    script: ./performance.yaml
  - teststrategy: functional
    script: ./func.yaml
```
